# Nom de notre workflow
name: "Github pages"

# Événements sur lesquels il doit être déclenché
on:
  push:         # <- Déclenché lorsque l'on pousse du code...
    branches:
      - main  # <- ... mais seulement sur la branche "master"

jobs:
  # Notre job
  build-and-deploy:
    runs-on: ubuntu-latest
    # Tâches à effectuer, comme expliquées ci-dessus
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      # 1. Partie Build
      - name: "Build"
        run: |
          npm ci
          npm run build
      # 2. Déploiement sur les Github Pages
      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/  # <- Dossier contenant notre documentation générée
